config/routes.rb
Rails.application.routes.draw do
  resources :requests do
    member do
      get 'upvote'
    end
  end

  resources :users, only: [:index]
  resources :languages, only: [:index]

  get '/home', to: 'static#home'
  get '/about', to: 'static#about'

  get '/login', as: :login, to: 'users#login'

  get '/auth/:provider/callback', to: 'users#create'
  get '/logout', to: 'users#logout', as: :logout

  root to: 'requests#index'

end

app/models/language.rb
class Language < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :requests


  def request_from
    Request.by_language(self.id, 'from')
  end

  def request_to
    Request.by_language(self.id, 'to')
  end

  def self.search q
    results = where('slug LIKE ? OR slug LIKE ?', q.downcase, "#{q.downcase}_%")
    if results
      results.map { |result| {id: result.id, text: result.name} }
    end
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :works
  has_many :upvotes

  belongs_to :from_language, class_name: "Language", foreign_key: "from_language_id"
  belongs_to :to_language, class_name: "Language", foreign_key: "to_language_id"

  scope :interested_by, lambda {|id| joins(:upvotes).where('upvotes.user_id = ?', id) }

  def self.by_language(language_id, direction)
    direction = "#{direction}_language"
    where("#{direction} = ?", language_id)
  end

  def upvoted_by? user
    upvotes.find_by(user_id: user).present?
  end
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :user
  belongs_to :request
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :github_username, use: :slugged
  has_many :requests
  has_many :works
  has_many :upvotes
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :user
  belongs_to :request
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by_email(session[:email])
  end

  def user_logged_in?
    session[:email].present?
  end

  def require_login
    unless session[:email]
      redirect_to root_path
    end
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    render json: Language.search(params[:q])
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_user_request, only: [:edit, :update, :destroy]
  before_action :require_login, except: [:index, :show]

  def index
    @options = allow_options [:from, :to, :by, :interested]
    @requests = Request.includes(:from_language)
    @requests = @requests.where(from_language: find_language(@options[:from])) if @options[:from].present?
    @requests = @requests.where(to_language: find_language(@options[:to])) if @options[:to].present?
    if @options[:by].present?
      user = User.friendly.find(@options[:by])
      @requests = @requests.where(user: user)
    end
    if @options[:interested].present?
      user = User.friendly.find(@options[:interested])
      @requests = @requests.interested_by user.id
    end
    if user_logged_in?
      @upvoted_requests = current_user.upvotes.collect(&:request).compact.uniq
    else
      @upvoted_requests = nil
    end
  end

  def show
    @request = Request.includes(:from_language, upvotes: :user).friendly.find(params[:id])
    @owner = @request.user
  end

  def new
    @request = current_user.requests.new
    @languages = Language.all
  end

  def edit
    @languages = Language.all
  end

  def create
    @request = current_user.requests.new(request_params)

    respond_to do |format|
      if @request.save
        @request.upvotes.create(user: current_user)
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @request = Request.friendly.find(params[:id])
    if upvoted = current_user.upvotes.where(request_id: Request.friendly.find(params[:id]).id) and upvoted.present?
      upvoted.destroy_all
      status_msg = "I too want this"
    else
      current_user.upvotes.create(request_id: Request.friendly.find(params[:id]).id)
      status_msg = "I don't want this"
    end
    render json: {status: status_msg, upvotes: @request.upvotes.count}
  end

  private
    def set_user_request
      @request = current_user.requests.friendly.find(params[:id])
    end

    def request_params
      params.require(:request).permit(:name, :url, :description, :from_language_id, :to_language_id)
    end

    def allow_options opts
      params.permit opts
    end

    def find_language lang
      Language.friendly.find(lang)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.find_by(:github_id => auth_hash.uid)
    unless @user.present?
      @user = User.create(github_hash)
    end
    session[:email] = @user.email
    redirect_to session[:redirect_url]
  end

  def logout
    reset_session
    redirect_to root_path
  end

  def login
    session[:redirect_url] = params[:redirect_uri] || root_path
    redirect_to '/auth/github'
  end

  private
  def auth_hash
    request.env['omniauth.auth']
  end

  def github_hash
    {
      :name => auth_hash.info["name"],
      :github_username => auth_hash.info["nickname"],
      :email => auth_hash.info["email"],
      :token => auth_hash.credentials["token"],
      :github_id => auth_hash.uid
    }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find_by_email(session[:email])
  end

  def user_logged_in?
    session[:email].present?
  end

  def is_owner? req
    if user_logged_in?
      req.user == current_user
    end
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper

  def filter_message options
    message = "<p>"
    message += "Ports from <i>#{options['from']}</i> " if options["from"].present?
    message += "to <i>#{options['to']}</i> " if options["to"].present?
    message += "requested by <i>#{options['by']}</i> " if options["by"].present?
    message += "upvoted by <i>#{options['interested']}</i> " if options["interested"].present?
    message
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_loginmodal.html.erb
<div class="modal" id="login-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title text-center">Please Sign in to Dumat</h4>
      </div>
      <div class="modal-body">
        <p class="text-center act-link login-btn" data-href=<%= login_path %>><i class="fa fa-github fa-5x"></i></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dumat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Dumat</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav navbar-right">
        <% if user_logged_in? %>
          <li><a><%= current_user.name %></a></li>
          <li><%= link_to 'Logout', logout_path %></li>
        <% else %>
          <li><%= link_to 'Login', login_path, data:{href: login_path}, class: 'login-btn' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

<%= render "common/loginmodal" %>
</body>
</html>

app/views/requests/_form.html.erb
<%= form_for @request, :html => {:class => 'form-control'} do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name, placeholder: "Library Name / Request name", class: 'form-control', required: true %>
    <br />
    <%= f.text_field :url, placeholder: "Library URL (github)", class: 'form-control', required: true%>
    <br />
    <%= f.text_area :description, placeholder: "Give a short description why the port or about the library", class: 'form-control', required: true %>
    <br />
    <%= f.text_field :from_language_id, class: 'language-selection', required: true, hidden: true, 'data-placeholder' => 'Select From Language' %>&nbsp;
    To &nbsp;<%= f.text_field "to_language_id", class: 'language-selection', required: true, hidden: true, 'data-placeholder' => 'Select To Language' %>
    <br /><br />
    <%= f.submit class: "btn btn-primary" %>&nbsp;&nbsp;<%= link_to 'Cancel', requests_path, class: 'btn btn-default' %>
<% end %>

app/views/requests/_people_panel.html.erb
<% upvotes = @request.upvotes.reject{|u| u.user == @owner } %>
<% if upvotes.present? %>
  <p><i><%= upvotes.count %> people are also interested in this..</i></p>
  <% upvotes.each do |upvote| %>
    <i><%= link_to upvote.user.slug, requests_path({"interested" => upvote.user}), class: 'link' %> showed interest on this <%= time_ago_in_words upvote.updated_at %> ago.</i><br />
  <% end %>
<% end %>
<hr />
<i><%= link_to @owner.slug, requests_path({"by" => @owner}), class: 'link' %> requested this <%= time_ago_in_words @request.created_at %> ago.</i>

app/views/requests/edit.html.erb
<div class="container-fluid">
  <div class="col-md-6 col-md-offset-1">
    <h4>New Request</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/requests/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <p id="notice"><%= notice %></p>
      <% unless @options.empty? %>
        <%= link_to "Clear Filters", requests_path, class: 'btn btn-warning' %><br /><br />
        <%= filter_message(@options).html_safe %>
      <% end %>
      <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-body">
          <% @requests.each do |req| %>
            <div class="panel panel-default">
              <div class="panel-body">
                <h5><%= link_to req.name, req, class: 'link' %></h5>
                <%= req.description %>
              </div>
              <div class="panel-footer">
                <%= link_to req.from_language.name, requests_path(@options.merge("from" => req.from_language.slug)), class: 'link' %> ->
                <%= link_to req.to_language.name, requests_path(@options.merge("to" => req.to_language.slug)), class: 'link' %>&nbsp; | &nbsp;
                <span class="upvotes-count"><%= req.upvotes.count %></span> people want this &nbsp;
                <% unless is_owner? req %>
                   | &nbsp;
                  <% if @upvoted_requests.present? and @upvoted_requests.include?(req) %>
                    <%= link_to "I don't want this", upvote_request_path(req), data: {allow: user_logged_in?}, class: 'link upvote-btn' %>
                  <% else %>
                    <%= link_to "I too want this", upvote_request_path(req), data: {allow: user_logged_in?}, class: 'link upvote-btn' %>
                  <% end %>
                <% end %>
                <div class="pull-right">
                  <i><%= link_to req.user.slug, requests_path(@options.merge("by" => req.user.slug)), class: 'link' %></i>&nbsp;
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="panel">
        <div class="panel-body">
          <% if user_logged_in? %>
            <% if @upvoted_requests.count > 0 %>
              <p><i>Projects you are interested in..</i></p>
              <% @upvoted_requests.each do |ureq| %>
                <p>
                <%= link_to ureq.name, ureq, class: 'link' %> - from <%= ureq.from_language.name %> to
                <%= ureq.to_language.name %></p>
              <% end %>
            <% else %>
              <p>When you show interest in some project, it will show here</p>
            <% end %>
          <% else %>
            <p>
            dumat is web tool where you can request for open source
            library ports from one language to the other. Or can request
            for a new library altogether.
            </p>

            <hr />
            <b>How it Works:-</b>
            <ol>
              <li>You create a Request for a library port.</li>
              <li>People who also wants a similar port upvotes it.</li>
              <br /><i>Upcoming</i><br /><br />
              <li>People who wish to port can assign and work on it.</li>
            </ol>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-2">
      <% if user_logged_in? %>
        <%= link_to 'New Request', new_request_path, class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/requests/new.html.erb
<div class="container-fluid">
  <div class="col-md-6 col-md-offset-1">
    <h4>New Request</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/requests/show.html.erb
<% upvote_msg = @request.upvoted_by?(current_user) ? "I don't want this" : "I too want this" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p id="notice"><%= notice %></p>
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title"><%= @request.name %>
          <div class="pull-right"><%= link_to @request.from_language.name, requests_path({"from" => @request.from_language}), class: 'link' %> To
          <%= link_to @request.to_language.name, requests_path({"to" => @request.to_language}), class: 'link' %></div>
          </div>
        </div>
        <div class="panel-body">
          <p><i class="fa fa-external-link"></i> <a href=<%= @request.url %> class="link"><%= @request.url %></a></p>
          <hr />
          <%= @request.description %>
        </div>
        <div class="panel-footer">
          <span class="upvotes-count"><%= @request.upvotes.count %></span> people want this
          &nbsp;
          <% unless is_owner? @request %>
            | &nbsp;
              <%= link_to upvote_msg, upvote_request_path(@request), data: {allow: user_logged_in?}, class: 'upvote-btn link' %>
          <% end %>
          <% if user_logged_in? and @owner == current_user %>
            <div class="pull-right">
              <a href=<%= edit_request_path(@request) %> class='link'><i class="fa fa-pencil"></i></a>&nbsp; | &nbsp;
              <%= link_to ('<i class="fa fa-trash-o"></i>').html_safe,  @request,  method: :delete, data: { confirm: 'Are you sure?' }, class: 'link' %>
            </div>
          <% end %>
        </div>
      </div>
      <%= render 'people_panel'%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% user_upvoted = @user.upvotes.count - @user.requests.count %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @user.slug %>
          <span class="pull-right"><i>joined on <%= @user.created_at.to_date %></i></span></h3>
        </div>
        <div class="panel-body">
          <%= @user.slug %> has <%= link_to "#{@user.requests.count} requests", requests_path({"by" => @user}, class: 'link') %>
          <% if user_upvoted > 1 %>
            and interested in other <%= link_to "#{user_upvoted} requests", requests_path({"interested" => @user}), class: 'link' %>.
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>